app:
  name: "voucher-ms"
  version: 0.1

http:
  port: "5000"
  read-timeout: "10s"
  write-timeout: "10s"

database:
  host: "voucher-db"
  port: 5432
  user: "user"
  password: "password"
  name: "voucher_db"

redis:
  host: "redis"
  port: "6379"
  password: "mypassword"
