app:
  name: "promotion-ms"
  version: 0.1

http:
  port: "4000"
  read-timeout: "10s"
  write-timeout: "10s"

database:
  host: "db"
  port: 5432
  user: "user"
  password: "password"
  name: "promotion_db"

redis:
  host: "127.0.0.1"
  port: "6379"
  password: "mypassword"

voucher:
  host: "127.0.0.1"
  port: "5001"
  endpoint: "v1/vouchers"
  healthz: "v1/healthz"
