services:
  voucher-server:
    build:
      context: .
      target: final
    volumes:
      - ./config/config.yaml:/config.yaml
    ports:
      - 5001:5000
    expose:
      - 5000
    depends_on:
      - wait_for_dependencies
    networks:
      - promotion-bridge-network

  wait_for_dependencies:
    image: busybox
    volumes:
      - ./wait-for.sh:/wait-for.sh
    command: ["sh", "-c", "./wait-for.sh voucher-db:5432 -t 15"]
    depends_on:
      voucher-db:
        condition: service_healthy

  voucher-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=voucher_db
    ports:
      - 5435:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - voucher-db-data:/var/lib/postgresql/data
    networks:
      - promotion-bridge-network

volumes:
  voucher-db-data:

networks:
  promotion-bridge-network:
    external: true
