services:
  # server:
  #   build:
  #     context: .
  #     target: final
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     db:
  #       condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=voucher_db
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - voucher-db-data:/var/lib/postgresql/data

volumes:
  voucher-db-data:
