services:
  server:
    build:
      context: .
      target: final
    volumes:
      - ./config/config.yaml:/config.yaml
    ports:
      - 3000:3000
    depends_on:
      - wait_for_dependencies
    networks:
      - ekyc-network

  wait_for_dependencies:
    image: busybox
    volumes:
      - ./wait-for.sh:/wait-for.sh
    command: ["sh", "-c", "/wait-for.sh postgres:5432 -t 60"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres
    container_name: ekyc-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ekyc_db
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ekyc-db-data:/var/lib/postgresql/data
    networks:
      - ekyc-network

  redis:
    container_name: "redis"
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass mypassword
    ports:
      - 6379:6379
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  ekyc-db-data:

networks:
  ekyc-network:
    driver: bridge
