app:
  name: "ekyc-ms"
  version: 0.1

http:
  port: "3000"
  read-timeout: "10s"
  write-timeout: "10s"

database:
  host: "ekyc-db"
  port: 5432
  user: "user"
  password: "password"
  name: "ekyc_db"

jwt:
  issuer: "ekyc-ms"
  secret: "manofsteel"

redis:
  host: "redis"
  port: "6379"
  password: "mypassword"
