services:
  promotion-server:
    build:
      context: .
      target: final
    volumes:
      - ./config/config.yaml:/config.yaml
    ports:
      - 4001:4000
    depends_on:
      - wait_for_dependencies
    networks:
      - promotion-bridge-network

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
      target: final
    volumes:
      - ./config/config.yaml:/config.yaml
    depends_on:
      - wait_for_dependencies
    networks:
      - promotion-bridge-network

  wait_for_dependencies:
    image: busybox
    volumes:
      - ./wait-for.sh:/wait-for.sh
    command: ["sh", "-c", "./wait-for.sh promotion-db:5432 -t 15 -- echo '~~'"]
    depends_on:
      promotion-db:
        condition: service_healthy

  promotion-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=promotion_db
    ports:
      - 5434:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - promotion-db-data:/var/lib/postgresql/data
    networks:
      - promotion-bridge-network

volumes:
  promotion-db-data:

networks:
  promotion-bridge-network:
    external: true
